name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r backend/requirements.txt
        working-directory: backend

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest backend/tests/
        working-directory: backend

      - name: Linting with flake8
        run: |
          source venv/bin/activate
          flake8 backend
        working-directory: backend

      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "GitHub Actions: Job ${{ job.status }} for ${{ github.repository }} by ${{ github.actor }}"
